#ifndef __AUTO_VERSION_HEADER
#define __AUTO_VERSION_HEADER

#define VERSION_MAJOR_RELEASE			1
#define VERSION_MINOR_RELEASE			4
#define VERSION_INTERNAL_BUILD			0
#define VERSION_BUILD_NUMBER			2394

#define VERSION_STRING					"1, 4, 0, 2394"
#define VERSION_STRING_DOTTED			"1.4.0"

#endif // __AUTO_VERSION_HEADER
